### ISSUE TITLE
MPC Modelle auf Papier

### ISSUE THREAD

**Issue by EvgenyKusmenko** [EmbeddedMontiArc/MontiMath#12]
inkl. Optimierungsfunktion

**Comment by ChristophRichter92** [comment]
![mpc_bicycle_1](https://user-images.githubusercontent.com/4721248/35047981-f44f6012-fb9b-11e7-8754-e05d283e4171.png)
![mpc_bicycle_2](https://user-images.githubusercontent.com/4721248/35047982-f4682994-fb9b-11e7-9aa0-1f5c189b46bb.png)
![mpc_bicycle_3](https://user-images.githubusercontent.com/4721248/35047984-f47fd062-fb9b-11e7-8a54-0536e9d1a1ce.png)
